// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CheckboxSelectAllController from "./checkbox_select_all_controller"
application.register("checkbox-select-all", CheckboxSelectAllController)

import InvoiceValueCalculatorController from "./invoice_value_calculator_controller"
application.register("invoice-value-calculator", InvoiceValueCalculatorController)

import ItemValueCalculatorController from "./item_value_calculator_controller"
application.register("item-value-calculator", ItemValueCalculatorController)

import MasksController from "./masks_controller"
application.register("masks", MasksController)

import ReplacementDiscountLineController from "./replacement_discount_line_controller"
application.register("replacement-discount-line", ReplacementDiscountLineController)

import Select2Controller from "./select2_controller"
application.register("select2", Select2Controller)

import SetActiveLinkController from "./set_active_link_controller"
application.register("set-active-link", SetActiveLinkController)

import SubmitOnChangeController from "./submit_on_change_controller"
application.register("submit-on-change", SubmitOnChangeController)
