development:
  secret_key_base: super_long_secret_key_for_development_renato_fairbanks
  google_client_id: 808409083618-ve6nvh56r28jgcmv2ijnh5a463p91nmv.apps.googleusercontent.com
  google_client_secret: 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